# Generated by Django 2.2.7 on 2019-11-22 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizz_app', '0001_initial'),
        ('specialisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzs', to='specialisation.Specialite'),
        ),
        migrations.AddField(
            model_name='question',
            name='quizz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizz_app.Quizz'),
        ),
    ]
