# Generated by Django 2.2.7 on 2019-11-23 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0002_auto_20191122_2330'),
        ('specialisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ('date_add',), 'verbose_name': 'Cours', 'verbose_name_plural': 'Courss'},
        ),
        migrations.AlterModelOptions(
            name='epreuve',
            options={'ordering': ('date_add',), 'verbose_name': 'Epreuve', 'verbose_name_plural': 'Epreuves'},
        ),
        migrations.AddField(
            model_name='epreuve',
            name='quizz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epreuve_quizz', to='quizz_app.Quizz'),
        ),
        migrations.AlterField(
            model_name='resultatepreuve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultat_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
