# Generated by Django 2.2.7 on 2019-11-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livecoding', '0002_auto_20191123_1347'),
        ('specialisation', '0002_auto_20191123_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuve',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultat_code', to='livecoding.Exercice'),
        ),
        migrations.AddField(
            model_name='resultatepreuve',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultat_code', to='livecoding.ResultatExercice'),
        ),
    ]
