# Generated by Django 2.2.7 on 2019-11-23 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialisation', '0002_auto_20191123_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.CharField(max_length=30, null=True)),
                ('genre', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('pays', models.CharField(max_length=255, null=True)),
                ('ville', models.CharField(max_length=255, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('images', models.ImageField(upload_to='images/avatar/')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
