# Generated by Django 2.2.7 on 2019-11-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0003_auto_20191123_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epreuve',
            old_name='exercice',
            new_name='code',
        ),
    ]
