# Generated by Django 2.2.7 on 2019-11-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatepreuve',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='resultatepreuve',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='resultatepreuve',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
