# Generated by Django 2.2.7 on 2019-11-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0005_auto_20191123_1331'),
        ('specialisation', '0004_auto_20191123_1352'),
    ]

    operations = [
    ]
