# Generated by Django 2.2.7 on 2019-11-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0006_merge_20191123_1512'),
        ('specialisation', '0006_merge_20191123_1505'),
    ]

    operations = [
    ]
