# Generated by Django 2.2.7 on 2019-11-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0008_auto_20191123_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultat_code', to='livecoding.Code'),
        ),
    ]
