# Generated by Django 2.2.7 on 2019-11-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0009_auto_20191123_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Cours', 'verbose_name_plural': 'Courss'},
        ),
    ]
