# Generated by Django 2.2.7 on 2019-11-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0010_auto_20191125_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epreuve',
            name='code',
        ),
        migrations.RemoveField(
            model_name='resultatepreuve',
            name='code',
        ),
    ]
