# Generated by Django 2.2.7 on 2019-11-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0012_auto_20191125_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultatepreuve',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultat_code', to='livecoding.ResultatCompo'),
        ),
    ]
