# Generated by Django 2.2.7 on 2019-11-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0013_auto_20191125_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatepreuve',
            name='moyenne',
            field=models.FloatField(null=True),
        ),
    ]
