# Generated by Django 2.2.7 on 2019-11-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0014_resultatepreuve_moyenne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultatepreuve',
            name='moyenne',
        ),
    ]
