# Generated by Django 2.2.7 on 2019-11-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0015_remove_resultatepreuve_moyenne'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatepreuve',
            name='user_moyenne',
            field=models.FloatField(db_column='moyenne', null=True),
        ),
    ]
