# Generated by Django 2.2.7 on 2019-11-28 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0017_remove_resultatepreuve_user_moyenne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='epreuve',
        ),
        migrations.AddField(
            model_name='epreuve',
            name='cours',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='epreuve_cours', to='specialisation.Cours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ressourcepdf',
            name='titre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
