# Generated by Django 2.2.7 on 2019-11-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0018_auto_20191128_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressourcevideo',
            name='titre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
