# Generated by Django 2.2.7 on 2019-11-28 10:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0019_ressourcevideo_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', tinymce.models.HTMLField(verbose_name='contenu')),
            ],
            options={
                'verbose_name': 'Testcode',
                'verbose_name_plural': 'Testcodes',
            },
        ),
    ]
