# Generated by Django 2.2.7 on 2019-11-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0020_testcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testcode',
        ),
        migrations.AddField(
            model_name='resultatepreuve',
            name='user_moyenne',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
