# Generated by Django 2.2.7 on 2019-11-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0021_auto_20191129_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultatepreuve',
            name='user_moyenne',
        ),
    ]
