# Generated by Django 2.2.7 on 2019-11-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livecoding', '0002_auto_20191123_1331'),
        ('livecoding', '0002_auto_20191123_1347'),
    ]

    operations = [
    ]
