# Generated by Django 2.2.7 on 2019-11-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0008_auto_20191123_1647'),
        ('livecoding', '0004_merge_20191123_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='specialite',
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('niveau', models.PositiveIntegerField()),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialitecode', to='specialisation.Specialite')),
            ],
            options={
                'verbose_name': 'Code',
                'verbose_name_plural': 'Codes',
            },
        ),
    ]
