# Generated by Django 2.2.7 on 2019-11-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livecoding', '0006_auto_20191123_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coding', to='livecoding.Code'),
            preserve_default=False,
        ),
    ]
