# Generated by Django 2.2.7 on 2019-11-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecoding', '0007_exercice_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='titre_slug',
            field=models.SlugField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
