# Generated by Django 2.2.7 on 2019-11-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecoding', '0008_exercice_titre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='titre_slug',
            field=models.SlugField(editable=False, max_length=255, null=True),
        ),
    ]
