# Generated by Django 2.2.7 on 2019-11-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livecoding', '0009_auto_20191125_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livecoding', to='livecoding.Code'),
        ),
    ]
