# Generated by Django 2.2.7 on 2019-11-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0011_auto_20191125_1209'),
        ('livecoding', '0010_auto_20191125_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='code',
        ),
        migrations.RemoveField(
            model_name='resultatcompo',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='resultatcompo',
            name='resultat_exercice',
        ),
        migrations.RemoveField(
            model_name='resultatcompo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resultatexercice',
            name='exercice',
        ),
        migrations.RemoveField(
            model_name='resultatexercice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testvalidation',
            name='exercice',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='Exercice',
        ),
        migrations.DeleteModel(
            name='ResultatCompo',
        ),
        migrations.DeleteModel(
            name='ResultatExercice',
        ),
        migrations.DeleteModel(
            name='TestValidation',
        ),
    ]
