# Generated by Django 2.2.7 on 2019-11-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livecoding', '0013_auto_20191125_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangageId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_id', models.PositiveIntegerField()),
                ('nom', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LangageId',
                'verbose_name_plural': 'LangageId',
                'ordering': ('date_add',),
            },
        ),
        migrations.RemoveField(
            model_name='code',
            name='niveau',
        ),
        migrations.AddField(
            model_name='resultatexercice',
            name='valider',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Langage_id',
        ),
        migrations.AddField(
            model_name='code',
            name='coding_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codingin', to='livecoding.LangageId'),
        ),
    ]
