# Generated by Django 2.2.7 on 2019-11-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecoding', '0014_auto_20191126_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='consige',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='debut',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='resultatcompo',
            name='nbr_exo_valider',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultatcompo',
            name='note',
            field=models.IntegerField(default=0),
        ),
    ]
