# Generated by Django 2.2.7 on 2019-11-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecoding', '0016_auto_20191127_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='consige',
            field=models.TextField(null=True, verbose_name='consigne a respecter'),
        ),
    ]
